apiVersion: v2
name: my-helm-chart
description: A Helm chart for deploying my application
version: 0.1.0

deploymentName: ninja-ai-service
replicaCount: 1
namespace: ninja-ai-service-dev
configMapName: ninja-ai-service-config
containerPort: 8083

image:
  repository: ninja-ai-service
  pullPolicy: IfNotPresent
  tag: "0.0.1"

service:
  type: LoadBalancer
  port: 8083
  targetPort: 8083