apiVersion: <apiVersion>
name: <name>
description: <description>
version: <version>

deploymentName: <deploymentName>
replicaCount: <replicaCount>
namespace: <namespace>
configMapName: <configMapName>
containerPort: <containerPort>

aws:
  region: <awsRegion>

image:
  repository: <repository>
  pullPolicy: <pullPolicy>
  tag: <imageTag>

service:
  type: <serviceType>
  port: <servicePort>
  targetPort: <targetPort>